package de.juliusawen.coastercreditcounter.userInterface.contentRecyclerViewAdapter;

public interface IDecorableExpandableContentRecyclerViewAdapter extends IDecorableContentRecyclerViewAdapter, IExpandableContentRecyclerViewAdapter
{
}
