package de.juliusawen.coastercreditcounter.tools.menuAgents;

public enum OptionsItem
{
    NO_FUNCTION,


    //NORMAL MENU ITEMS

    HELP,

    EXPAND_ALL,
    COLLAPSE_ALL,


    SORT,

    SORT_ASCENDING,
    SORT_DESCENDING,

    SORT_ATTRACTION_CATEGORIES,
    SORT_MANUFACTURERS,
    SORT_STATUSES,

    SORT_BY,

    SORT_BY_NAME,
    SORT_BY_NAME_ASCENDING,
    SORT_BY_NAME_DESCENDING,

    SORT_BY_LOCATION,
    SORT_BY_LOCATION_ASCENDING,
    SORT_BY_LOCATION_DESCENDING,

    SORT_BY_ATTRACTION_CATEGORY,
    SORT_BY_ATTRACTION_CATEGORY_ASCENDING,
    SORT_BY_ATTRACTION_CATEGORY_DESCENDING,

    SORT_BY_MANUFACTURER,
    SORT_BY_MANUFACTURER_ASCENDING,
    SORT_BY_MANUFACTURER_DESCENDING,


    GROUP_BY,
    GROUP_BY_LOCATION,
    GROUP_BY_MANUFACTURER,
    GROUP_BY_ATTRACTION_CATEGORY,
    GROUP_BY_STATUS,


    //ACTION MENU ITEMS

    GO_TO_CURRENT_VISIT,
    ENABLE_EDITING,
    DISABLE_EDITING,
}
