package de.juliusawen.coastercreditcounter.userInterface.contentRecyclerViewAdapter.adapter.interfaces;

public interface IDecorableExpandableContentRecyclerViewAdapter extends IDecorableContentRecyclerViewAdapter, IExpandableContentRecyclerViewAdapter
{
}
