package de.juliusawen.coastercreditcounter.userInterface.contentRecyclerViewAdapter.adapter.interfaces;

public interface IExpandableContentRecyclerViewAdapter extends IContentRecyclerViewAdapter
{
}
