package de.juliusawen.coastercreditcounter.userInterface.contentRecyclerViewAdapter.adapter.interfaces;

public interface ISelectableContentRecyclerViewAdapter extends IContentRecyclerViewAdapter
{
}
